// This file is auto-generated by `ember build`.
// You should not modify it.

require('./vendor/jquery');
require('./vendor/handlebars');
require('./vendor/ember');
require('./vendor/ember-data');
require('./templates');

var App = window.App = require('./app');

App.Store = require('./store');

App.EditPersonController = require('./controllers/edit_person_controller');
App.NewPersonController = require('./controllers/new_person_controller');
App.PersonController = require('./controllers/person_controller');
App.Person = require('./models/person');
App.NewPersonRoute = require('./routes/new_person_route');
App.PeopleRoute = require('./routes/people_route');

require('./routes');

